version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  restful:
    image: romanowalex/restful:v1.2-nginx
    container_name: restful
    environment:
      SPRING_PROFILES_ACTIVE: nginx
    ports:
      - 8180:8080
    depends_on:
      - postgres

  nginx:
    image: nginx:1.21
    container_name: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - restful

volumes:
  db-data: