version: "3"
services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site:/var/www:ro